In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 100)

print("Setup completed successfully!")

Setup completed successfully!

In [2]:
jobs = pd.read_csv ("C:/Users/lenovo/OneDrive/Desktop/Projects/Job Market Intelligence/data/raw/gsearch_jobs (1).csv")

jobs.head()

,Unnamed: 0,index,title,company_name,location,via,description,extensions,job_id,thumbnail,posted_at,schedule_type,work_from_home,salary,search_term,date_time,search_location,commute_time,salary_pay,salary_rate,salary_avg,salary_min,salary_max,salary_hourly,salary_yearly,salary_standardized,description_tokens
0,0,0,Data Analyst,Meta,Anywhere,via LinkedIn,"In the intersection of compliance and analytics, we are seeking an analytical and data-savvy sel...","['15 hours ago', '101K–143K a year', 'Work from home', 'Full-time']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2NpZCI6IlhBR01sSV93cUdRQUFBQUFBQUFBQUE9PSIsInV1bGUi...,https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGWd4ZbDsuXA2YQ7fwMam4nW4cokBZJJYHlWXaRfs&s,15 hours ago,Full-time,True,101K–143K a year,data analyst,2023-08-04 03:00:13.797776,United States,NaN,101K–143K,a year,122000.0,101000.0,143000.0,NaN,122000.0,122000.0,"['tableau', 'r', 'python', 'sql']"
1,1,1,Data Analyst,ATC,United States,via LinkedIn,Job Title: Entry Level Business Analyst / Product Owner U.S. Citizens and those authorized to wo...,"['12 hours ago', 'Full-time', 'Health insurance']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2NpZCI6InJ4WUhwWTd4aTNRQUFBQUFBQUFBQUE9PSIsInV1bGUi...,https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9pL2p8JqLIXvaGeM9_bc7EXVkXWuBzWI204SfKIU&s,12 hours ago,Full-time,NaN,NaN,data analyst,2023-08-04 03:00:13.797776,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
2,2,2,Aeronautical Data Analyst,"Garmin International, Inc.","Olathe, KS",via Indeed,"Overview:\n\nWe are seeking a full-time...\nAeronautical Data Analyst in our Olathe, KS location...","['18 hours ago', 'Full-time']",eyJqb2JfdGl0bGUiOiJBZXJvbmF1dGljYWwgRGF0YSBBbmFseXN0IiwiaHRpZG9jaWQiOiJtU2xQSUxycndaY0FBQUFBQUFB...,NaN,18 hours ago,Full-time,NaN,NaN,data analyst,2023-08-04 03:00:13.797776,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['sql']
3,3,3,Data Analyst - Consumer Goods - Contract to Hire,Upwork,Anywhere,via Upwork,Enthusiastic Data Analyst for processing sales data in Excel and communicate with clients. Hours...,"['12 hours ago', '15–25 an hour', 'Work from home', 'Contractor', 'No degree mentioned']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgLSBDb25zdW1lciBHb29kcyAtIENvbnRyYWN0IHRvIEhpcmUiLCJodGlkb2Np...,NaN,12 hours ago,Contractor,True,15–25 an hour,data analyst,2023-08-04 03:00:13.797776,United States,NaN,15–25,an hour,20.0,15.0,25.0,20.0,NaN,41600.0,"['powerpoint', 'excel', 'power_bi']"
4,4,4,Data Analyst | Workforce Management,Krispy Kreme,United States,via LinkedIn,Overview of Position\n\nThis position will be the primary person responsible for all Workforce M...,"['7 hours ago', '90K–110K a year', 'Contractor']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgfCBXb3JrZm9yY2UgTWFuYWdlbWVudCIsImh0aWRvY2lkIjoibUhMMHlaX1Rr...,https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRV1lShEQRsstSpp3yi846fCWv72q10JAm0_pNpHc&s,7 hours ago,Contractor,NaN,90K–110K a year,data analyst,2023-08-04 03:00:13.797776,United States,NaN,90K–110K,a year,100000.0,90000.0,110000.0,NaN,100000.0,100000.0,"['powerpoint', 'excel', 'outlook', 'word']"

Check Dataset Shape

In [3]:
jobs.shape

(61953, 27)

Inspect Data Types

In [4]:
jobs.info()

<class 'pandas.DataFrame'>
RangeIndex: 61953 entries, 0 to 61952
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           61953 non-null  int64
 1   index                61953 non-null  int64
 2   title                61953 non-null  str
 3   company_name         61953 non-null  str
 4   location             61916 non-null  str
 5   via                  61944 non-null  str
 6   description          61953 non-null  str
 7   extensions           61953 non-null  str
 8   job_id               61953 non-null  str
 9   thumbnail            38194 non-null  str
 10  posted_at            61763 non-null  str
 11  schedule_type        61707 non-null  str
 12  work_from_home       27980 non-null  object
 13  salary               10088 non-null  str
 14  search_term          61953 non-null  str
 15  date_time            61953 non-null  str
 16  search_location      61953 non-null  str
 17  commute_time         0 non-null      float64
 18  salary_pay           10088 non-null  str
 19  salary_rate          10088 non-null  str
 20  salary_avg           10088 non-null  float64
 21  salary_min           9512 non-null   float64
 22  salary_max           9512 non-null   float64
 23  salary_hourly        5900 non-null   float64
 24  salary_yearly        4069 non-null   float64
 25  salary_standardized  10088 non-null  float64
 26  description_tokens   61953 non-null  str
dtypes: float64(7), int64(2), object(1), str(17)
memory usage: 12.8+ MB

View Column Names

In [5]:
jobs.columns

Index(['Unnamed: 0', 'index', 'title', 'company_name', 'location', 'via',
       'description', 'extensions', 'job_id', 'thumbnail', 'posted_at',
       'schedule_type', 'work_from_home', 'salary', 'search_term', 'date_time',
       'search_location', 'commute_time', 'salary_pay', 'salary_rate',
       'salary_avg', 'salary_min', 'salary_max', 'salary_hourly',
       'salary_yearly', 'salary_standardized', 'description_tokens'],
      dtype='str')

View Random Records

In [6]:
jobs.sample(5)

,Unnamed: 0,index,title,company_name,location,via,description,extensions,job_id,thumbnail,posted_at,schedule_type,work_from_home,salary,search_term,date_time,search_location,commute_time,salary_pay,salary_rate,salary_avg,salary_min,salary_max,salary_hourly,salary_yearly,salary_standardized,description_tokens
40440,40440,1240,Digital Strategy Data Analyst,Missouri State Job Bank,Missouri,via Vacancies For Col U Fans,"Equifax is where you can power your possible. If you want to achieveyour true potential, chart n...","['16 hours ago', 'Full-time']",eyJqb2JfdGl0bGUiOiJEaWdpdGFsIFN0cmF0ZWd5IERhdGEgQW5hbHlzdCIsImh0aWRvY2lkIjoidC1NMnc2Ym9LRzRBQUFB...,NaN,16 hours ago,Full-time,NaN,NaN,data analyst,2022-12-14 04:00:31.780415,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
308,308,308,Data Engineer,Impact Advisors,United States,via LinkedIn,"Healthcare Data Engineer\n\nWork You’ll Do...\n\nAs a Healthcare Data Engineer, you will work cl...","['16 hours ago', 'Full-time']",eyJqb2JfdGl0bGUiOiJEYXRhIEVuZ2luZWVyIiwiaHRpZG9jaWQiOiJBTEdNbnVnUHhGOEFBQUFBQUFBQUFBPT0iLCJ1dWxl...,https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbO4yshVOdkUHrKj60cyu6PcPtanlRhYRE96pFyH8&s,16 hours ago,Full-time,NaN,NaN,data analyst,2023-08-03 03:00:44.080602,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['tableau', 'power_bi', 'bigquery', 'looker', 'sap', 'ssis', 'snowflake', 'hadoop', 'spark', 'sq..."
34364,34364,2321,Data Analyst for Real Estate Market Reports,Upwork,Anywhere,via Upwork,We are a real estate business specializing in build-to-rent properties in multiple regions of Fl...,"['11 hours ago', '20–50 an hour', 'Work from home', 'Contractor and Temp work', 'No degree menti...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgZm9yIFJlYWwgRXN0YXRlIE1hcmtldCBSZXBvcnRzIiwiaHRpZG9jaWQiOiJV...,NaN,11 hours ago,Contractor and Temp work,True,20–50 an hour,data analyst,2023-10-24 03:00:18.968980,United States,NaN,20–50,an hour,35.0,20.0,50.0,35.0,NaN,72800.0,['go']
46275,46275,635,I need an urgent statistical test analysis that may require...,Upwork,Anywhere,via Upwork,I need an urgent statistical work (run the tests for the data) and if possible to write the repo...,"['14 hours ago', 'Work from home', 'Contractor']",eyJqb2JfdGl0bGUiOiJJIG5lZWQgYW4gdXJnZW50IHN0YXRpc3RpY2FsIHRlc3QgYW5hbHlzaXMgdGhhdCBtYXkgcmVxdWly...,NaN,14 hours ago,Contractor,True,NaN,data analyst,2023-05-01 03:00:20.516375,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['spss']
4156,4156,1870,Analyst consumer,Consolidated Communications,"Chouteau, OK",Talent.com,Major Duties\n\nClassification : Exempt / Non-Bargaining\n\nJoin a team that offers growth poten...,"['21 hours ago', '55,882–84,714 a year', 'Full-time', 'Dental insurance', 'Paid time off', 'Heal...",eyJqb2JfdGl0bGUiOiJBbmFseXN0IGNvbnN1bWVyIiwiY29tcGFueV9uYW1lIjoiQ29uc29saWRhdGVkIENvbW11bmljYXRp...,NaN,21 hours ago,Full-time,NaN,"55,882–84,714 a year",data analyst,2024-09-17 20:47:43.156149,United States,NaN,55882–84714,a year,70298.0,55882.0,84714.0,NaN,70298.0,70298.0,"['tableau', 'excel', 'spreadsheet', 'word']"

or it may be (head())

Summary Statistics

In [7]:
jobs.describe(include="all")

,Unnamed: 0,index,title,company_name,location,via,description,extensions,job_id,thumbnail,posted_at,schedule_type,work_from_home,salary,search_term,date_time,search_location,commute_time,salary_pay,salary_rate,salary_avg,salary_min,salary_max,salary_hourly,salary_yearly,salary_standardized,description_tokens
count,61953.000000,61953.000000,61953,61953,61916,61944,61953,61953,61953,38194,61763,61707,27980,10088,61953,61953,61953,0.0,10088,10088,10088.000000,9512.000000,9512.000000,5900.000000,4069.000000,10088.000000,61953
unique,NaN,NaN,23292,13429,1254,1024,42976,9668,58775,14686,109,32,1,2225,1,6588,1,NaN,2225,3,NaN,NaN,NaN,NaN,NaN,NaN,11276
top,NaN,NaN,Data Analyst,Upwork,Anywhere,via LinkedIn,"The Sr. Data Analyst, Marketing Operations will report to the Director of Marketing Operations a...","['17 hours ago', 'Full-time']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJjb21wYW55X25hbWUiOiJDaXR5IG9mIEdyYW5kIEp1bmN0aW9uIiwiYWRk...,https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRy7BDVLI1v0TTiEd_1-A9erQIeLXnbzmstT3FzCrk&s,18 hours ago,Full-time,True,77K–116K a year,data analyst,2023-08-04 03:00:13.797776,United States,NaN,77K–116K,an hour,NaN,NaN,NaN,NaN,NaN,NaN,[]
freq,NaN,NaN,6444,7533,18067,20475,258,841,75,3505,4132,45082,27980,413,61953,10,61953,NaN,413,5900,NaN,NaN,NaN,NaN,NaN,NaN,13352
mean,30976.000000,1139.077333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42100.231239,34846.281874,50487.856787,40.539588,104115.406718,92289.425683,NaN
std,17884.434951,690.256113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55893.993519,45843.034891,67366.522273,22.214540,36024.388492,43277.933820,NaN
min,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.250000,8.000000,10.000000,7.250000,29289.840000,15080.000000,NaN
25%,15488.000000,553.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.500000,19.520000,45.000000,23.265000,80000.180000,62400.000000,NaN
50%,30976.000000,1111.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.000000,50.000000,75.000000,33.500000,96500.000000,88400.000000,NaN
75%,46464.000000,1685.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92500.000000,77000.000000,110000.000000,55.000000,120000.000000,117500.000000,NaN
max,61952.000000,3228.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,550000.000000,450000.000000,850000.000000,300.000000,550000.000000,624000.000000,NaN

In [8]:
jobs[['Unnamed: 0', 'index']].head(10)

   Unnamed: 0  index
0           0      0
1           1      1
2           2      2
3           3      3
4           4      4
5           5      5
6           6      6
7           7      7
8           8      8
9           9      9

In [9]:
jobs['title'].head(10)

0                                        Data Analyst
1                                        Data Analyst
2                           Aeronautical Data Analyst
3    Data Analyst - Consumer Goods - Contract to Hire
4                 Data Analyst | Workforce Management
5                                        Data Analyst
6                     Data Analyst (Model Validation)
7                                        Data Analyst
8                      IT Financial Data Analyst Lead
9                                        Data Analyst
Name: title, dtype: str

In [10]:
jobs['title'].value_counts().head(20)

title
Data Analyst                              6444
Senior Data Analyst                       1748
Data Scientist                             931
Data Analyst II                            644
Business Data Analyst                      495
Lead Data Analyst                          428
Survey Data Analyst                        422
Data Engineer                              375
Business Intelligence Analyst              343
Data Analyst III                           284
Sr. Data Analyst, Marketing Operations     271
Sr. Data Analyst                           240
Financial Data Analyst                     227
Marketing Data Analyst                     223
Junior Data Analyst                        213
Business Analyst                           212
Data analyst                               163
Healthcare Data Analyst                    162
Data Analyst I                             159
Sr Data Analyst                            155
Name: count, dtype: int64

In [11]:
jobs['company_name'].unique()

<StringArray>
[                                    'Meta',
                                      'ATC',
               'Garmin International, Inc.',
                                   'Upwork',
                             'Krispy Kreme',
                    'Flint Hills Resources',
                                 'Swedbank',
                                      'AEG',
                              'Progressive',
                                  'Chloeta',
 ...
 'Business Advisory Solutions Group (BASG)',
    'Security Service Federal Credit Union',
                   'Icon Clinical Research',
                                'PINKERTON',
                              'Vastek Inc.',
                        'LUFKIN INDUSTRIES',
                           'stand together',
                             'Techveda Inc',
                   'Applied Memetics L.L.C',
                         'Techdash Telecom']
Length: 13429, dtype: str

In [12]:
jobs['company_name'].value_counts().head(10)

company_name
Upwork                7533
Talentify.io          2118
Walmart               1829
vmysmartpros          1415
Dice                   862
EDWARD JONES           747
Corporate              612
Cox Communications     538
Insight Global         483
iSay                   353
Name: count, dtype: int64

In [13]:
jobs['location'].nunique()

1254

In [14]:
jobs['location'].value_counts().head(10)

location
 Anywhere                  18067
  United States            10011
Anywhere                    9915
United States               5547
Denver, CO                  1062
  Oklahoma City, OK         1028
  Kansas City, MO            840
Kansas City, MO              573
  Jefferson City, MO         550
Colorado Springs, CO         512
Name: count, dtype: int64

In [15]:
jobs.isnull().sum().sort_values(ascending=False).head(10)

commute_time           61953
salary_yearly          57884
salary_hourly          56053
salary_max             52441
salary_min             52441
salary                 51865
salary_pay             51865
salary_rate            51865
salary_standardized    51865
salary_avg             51865
dtype: int64

In [16]:
jobs.duplicated().sum()

np.int64(0)

In [17]:
jobs['job_id'].nunique(),len(jobs)

(58775, 61953)